Run : CompressedTrie
	./CompressedTrie
CompressedTrie : CompressedTrie.o
	g++ -std=c++14 CompressedTrie.o -o CompressedTrie

CompressedTrie.o : CompressedTrie.cpp
	g++ -std=c++14 -c CompressedTrie.cpp 
